### ISSUE TITLE
Use `inherit` instead of carrying settings down manually

### ISSUE THREAD

**Issue by kennethormandy** [kennethormandy/normalize-opentype.css#8]
Need to test this more, but apparently this works in some places:

``` css
body {
  font-feature-settings: "kern" 1, "smcp" 1;
}

p {
  font-feature-settings: "smcp"; /* This acts like you wrote `"kern" 0;` which is annoying */
  font-feature-settings: "smcp" 1, "smcp" 1; /* What I’m doing now */
  font-feature-settings: "kern" inherit, "smcp" inherit; /* Verbose, but easier to maintain. */
}
```
